name = "HaveExtractor"
version = "0.1.0"
defaultTargets = ["haveextractor"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "HaveExtractor"

[[lean_exe]]
name = "haveextractor"
root = "Main"
